GET http://php-pro.loc/api/books
Accept: application/json


### Send POST request with json body
POST http://php-pro.loc/api/books
Accept: application/json
Content-Type: application/json

{
    "name": "MyBook",
    "year": 2007,
    "lang": "ua",
    "pages": 235
}
